# Generated by Django 4.2.5 on 2024-07-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_choice_percentage_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='percentage_correct',
        ),
        migrations.AlterField(
            model_name='result',
            name='progress',
            field=models.IntegerField(default=-1),
        ),
    ]
